apiVersion: v1
kind: Service
metadata:
  name: springboot-app-service
spec:
  type: NodePort
  selector:
    app: spring-boot-k8s  # Common label for both pods
  ports:
    - protocol: TCP
      port: 8080          # Port exposed inside the cluster
      targetPort: 8080    # Port where Spring Boot app is listening in the container
      nodePort: 30000     # NodePort on the Minikube node (optional, can be automatically assigned)
