apiVersion: v1
kind: Service
metadata:
  name: vote-service
  app: demo-voting-app
spec:
  type: NodePort
  selector:
    name: voting-app-pod
    app: demo-voting-app
  ports:
    - protocol: TCP
      port: 80         # Port exposed inside the cluster
      targetPort: 80    # Port where Spring Boot app is listening in the container
      nodePort: 30004